# -*- coding: utf-8 -*-
"""Clasificacion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-b6P75hvOJq8ZVdAlyeSIdYbUTnazspC
"""

def clasificacion_de_figuras(puntas):
    if puntas == 0:
        return "O"
    if puntas == 4:
        return "C"
    if puntas == 3:
        return "T"
    if puntas < 3 or puntas > 4:
        return "X"